{
    'name': 'Certification',
    'summary': "Defines certification for different purposes.",
    'author': "Abdulkadir-yilmaz",
    'website': "https://github.com/abdulkadir-yilmaz",
    'category': 'Certification Management',
    'version': '12.0.1.0.0',
    'License': 'AGPL-3',
    'depends': ['hr'],
    'data': ['security/ir.model.access.csv',
             'security/certification_security.xml',
            'views/certification_view.xml',
            'views/certification_bodies.xml',
            'views/identity_view.xml',
            'views/res_partner_view.xml',
            'views/standard_view.xml',
            'reports/certification_report.xml'
             ],
    'development_satus' : 'Beta',
    'maintainers' : ['abdulkadir-yilmaz'],
}